language: node_js
node_js:
    - 'stable'
before_install:
    - npm install -g codeclimate-test-reporter
    - npm install -g typescript
install:
    - npm install
script:
    - npm run build
deploy:
    provider: npm
    skip_cleanup: true
    email: $NPM_EMAIL
    api_key: $NPM_TOKEN
    on:
        tags: true
jobs:
    include:
	- stage: test
	  script: npm run test
	- stage: code-coverage
	  script: CODECLIMATE_REPO_TOKEN=$CODE_CLIMATE codeclimate-test-reporter < coverage/lcov.info
notifications:
  email:
    recipients:
    - sumanTitan@servicetitan.com
    - kanoshin@servicetitan.com
    on_success: change
    on_failure: always
