language: node_js
node_js:
    - 'stable'
before_install:
    - npm install -g typescript
install:
    - npm install
script:
    - npm run build
deploy:
    provider: npm 
    script: "npm publish --access public"
    on:
        tags: true
notifications:
  email:
    recipients:
    - sumanTitan@servicetitan.com
    - kanoshin@servicetitan.com
    on_success: change
    on_failure: always
