language: node_js
addons:
  code_climate:
    repo_token: $CODE_CLIMATE
node_js:
    - 'stable'
before_install:
    - npm install -g typescript
install:
    - npm install
script:
    - npm run test
    - npm run build
deploy:
    provider: npm
    skip_cleanup: true
    email: $NPM_EMAIL
    api_key: $NPM_TOKEN
    on:
        tags: true
cache:
  directories:
    - node_modules
after_script:
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
notifications:
  email:
    recipients:
    - sumanTitan@servicetitan.com
    - kanoshin@servicetitan.com
    on_success: change
    on_failure: always
